-- Copyright (C) 2023 Eccelerators GmbH
-- 
-- This code was generated by:
--
-- HxS Compiler 1.0.19-10671667
-- VHDL Extension for HxS 1.0.21-b962bd24
-- 
-- Further information at https://eccelerators.com/hxs
-- 
-- Changes to this file may cause incorrect behavior and will be lost if the
-- code is regenerated.
library ieee;
	use ieee.std_logic_1164.all;
	use ieee.numeric_std.all;

package BusDividerIfcPackage is

	type T_BusDividerIfcWishboneDown is
	record
		Adr : std_logic_vector(8 downto 0);
		Sel : std_logic_vector(3 downto 0);
		DatIn : std_logic_vector(31 downto 0);
		We : std_logic;
		Stb : std_logic;
		Cyc : std_logic;
	end record;
	
	type T_BusDividerIfcWishboneUp is
	record
		DatOut : std_logic_vector(31 downto 0);
		Ack : std_logic;
	end record;
	
	type T_BusDividerIfcTrace is
	record
		WishboneDown : T_BusDividerIfcWishboneDown;
		WishboneUp : T_BusDividerIfcWishboneUp;
		UnoccupiedAck : std_logic;
		TimeoutAck : std_logic;
	end record;
	
	type T_BusDividerIfcBusDividerBlkDown is
	record
		BusDelegate0Adr : std_logic_vector(8 downto 0);
		BusDelegate0Sel : std_logic_vector(3 downto 0);
		BusDelegate0We : std_logic;
		BusDelegate0Stb : std_logic;
		BusDelegate0DatIn : std_logic_vector(31 downto 0);
		BusDelegate0Cyc : std_logic;
		BusDelegate1Adr : std_logic_vector(8 downto 0);
		BusDelegate1Sel : std_logic_vector(3 downto 0);
		BusDelegate1We : std_logic;
		BusDelegate1Stb : std_logic;
		BusDelegate1DatIn : std_logic_vector(31 downto 0);
		BusDelegate1Cyc : std_logic;
	end record;
	
	type T_BusDividerIfcBusDividerBlkUp is
	record
		BusDelegate0DatOut: std_logic_vector(31 downto 0);
		BusDelegate0Ack : std_logic;
		BusDelegate1DatOut: std_logic_vector(31 downto 0);
		BusDelegate1Ack : std_logic;
	end record;
	
	constant BUSDIVIDERBLK_BASE_ADDRESS : std_logic_vector(8 downto 0) := "000000000";
	constant BUSDIVIDERBLK_SIZE : std_logic_vector(9 downto 0) := "1000000000";
	
	constant BUSDELEGATE0_BASE_ADDRESS : std_logic_vector(8 downto 0) := std_logic_vector("000000000" + unsigned(BUSDIVIDERBLK_BASE_ADDRESS));
	constant BUSDELEGATE0_SIZE : std_logic_vector(9 downto 0) := "0100000000";
	
	constant BUSDELEGATE1_BASE_ADDRESS : std_logic_vector(8 downto 0) := std_logic_vector("100000000" + unsigned(BUSDIVIDERBLK_BASE_ADDRESS));
	constant BUSDELEGATE1_SIZE : std_logic_vector(9 downto 0) := "0100000000";
	
end;
