# Copyright (C) 2023 Eccelerators GmbH
# 
# This code was generated by:
#
# HxS Compiler 1.0.19-10671667
# Python Extension for HxS 1.0.7-62bb9ef4
# 
# Further information at https://eccelerators.com/hxs
# 
# Changes to this file may cause incorrect behavior and will be lost if the
# code is regenerated.
	
	
# -----------------------------------------------------
# Addresses, widths, values and masks for direct access
# -----------------------------------------------------
BusDividerIfcAddressBusWidth = 9
BusDividerIfcDataBusWidth = 32

class BusDividerBlk:
    BusDividerBlkAddress = 0x000 
    BusDividerBlkSize = 0x200 

    @property
    def BusDelegate0Address(self):
        return (0x000 + self.BusDividerBlkAddress)

    BusDelegate0Size = 0x100



    @property
    def BusDelegate1Address(self):
        return (0x100 + self.BusDividerBlkAddress)

    BusDelegate1Size = 0x100

