/* Copyright (C) 2023 Eccelerators GmbH
   
   This code was generated by:
  
   HxS Compiler 1.0.19-10671667
   C Extension for HxS 1.0.24-85d98215
   
   Further information at https://eccelerators.com/hxs
   
   Changes to this file may cause incorrect behavior and will be lost if the
   code is regenerated.
*/	
	
#ifndef _BusDividerIfc_H
#define _BusDividerIfc_H

/* ----------------------------------------------------- */
/* Addresses, widths, values and masks for direct access */
/* ----------------------------------------------------- */
#define BusDividerIfcAddressBusWidth 9
#define BusDividerIfcDataBusWidth 32

#define BusDividerBlkAddress 0x000
#define BusDividerBlkSize 0x200

#define BusDelegate0Address (0x000 + BusDividerBlkAddress)
#define BusDelegate0Size 0x100


#define BusDelegate1Address (0x100 + BusDividerBlkAddress)
#define BusDelegate1Size 0x100


#endif
